
Required Datasets:
  1. Data/MoR_Stats_Tissue.csv generated from step1
  2. Data/Final_Candidates.csv generated from step5

```{r}
Tissue <- read.csv("../Data/MoR_Stats_Tissue.csv")[,-1]
Final_list <- read.csv("../Data/Final_Candidates.csv")
library(ggplot2)
library(gghighlight)
library(ggrepel)
library(scales)
```

```{r Figure1}
cutoff <- 0.03
#Label UBQ1, UBQ10, Act2, RBCS2B, LHB1B1, cab2
Tissue$Symbol <- NA
Tissue$Symbol[which(Tissue$AGI == "AT3G52590")] <- "UBQ1"
Tissue$Symbol[which(Tissue$AGI == "AT4G05320")] <- "UBQ10"
Tissue$Symbol[which(Tissue$AGI == "AT3G18780")] <- "Act2"
Tissue$Symbol[which(Tissue$AGI == "AT5G38420")] <- "RbcS2B"
#Tissue$Symbol[which(Tissue$AGI == "AT2G34430")] <- "LHB1B1"
#Tissue$Symbol[which(Tissue$AGI == "AT1G29920")] <- "Cab2"

Annotated_Tissue <- subset(Tissue, !is.na(Symbol))
#For cutoff 0.03 (No core type info)
ggplot(data = Tissue, mapping = aes(x = geom_mean, y = CV)) +
  geom_point(size = 2, alpha = 0.3, color = "#DDCC77") +
  scale_shape_manual(values = c(21,22,23,24,25,20)) +
  theme_classic() +
  scale_x_log10(labels = trans_format("log10", math_format(10^.x)))+
  annotation_logticks(base=10, sides = "bl") +
  scale_y_log10(breaks = c(0.1,round(quantile(Tissue$CV, cutoff), digits = 2), 0.3,1,3.0), labels = c("0.1", round(quantile(Tissue$CV, cutoff), digits = 2), "0.3","1","3.0")) +
  xlab(label = bquote(Geometric~Mean~(log[10]))) +
  ylab(label = bquote(Coefficient~of~Variation~(log[10]))) +
  guides(alpha = F) +
  labs(color = "Core Type", shape = "Core Type", fill = "Core Type") +
  gghighlight(CV <= quantile(Tissue$CV, cutoff))+
  geom_hline(yintercept=quantile(Tissue$CV, cutoff), linetype='dotted', col = 'red')+
  geom_point(data = Annotated_Tissue, mapping = aes(x = geom_mean, y = CV), size =2, alpha = 0.6, color = "black") +
  geom_text_repel(data = Annotated_Tissue, mapping = aes(label = Symbol), 
                  box.padding = 1,
                  show.legend = FALSE) + #this removes the 'a' from the legend
  
  theme(axis.text.y = element_text(color = c("black", "red", "black", "black", "black")),
        axis.ticks.y = element_line(color = c("black", "red", "black", "black", "black"),
                          size = c(.5, 1, .5,.5,.5))) +
  geom_point(data = Final_list, mapping = aes(x = geom_mean, y = CV), size = 2, alpha = 1, color = "#CC6677") +
  coord_cartesian(expand = TRUE, xlim = c(10, 1e5), ylim = c(0.1, 8))
```


```{r}
ggplot(data = Final_list, mapping = aes(x = geom_mean, y = CV)) +
  geom_point(size = 5, alpha = 0.4) +
  theme_classic() +
  scale_x_continuous(trans='log2', limits = c(256, 8192), breaks=scales::trans_breaks("log2", function(x) 2^x)) +
  scale_y_continuous(breaks=seq(0.12, 0.26, 0.02), limits = c(0.12,0.26)) +
  xlab(label = bquote(Geometric~Mean~(log[2]))) +
  ylab(label = "Coefficient of Variation") +
  theme(axis.title =element_text(family="sans"))

```